<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Home 10 Mbps',
                'internal_name' => 'home_10',
                'description' => 'Basic residential internet for light usage',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Residential',
                'download_speed' => 10,
                'upload_speed' => 5,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 200,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 15.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 5,
            ],
            [
                'name' => 'Home 50 Mbps',
                'internal_name' => 'home_50',
                'description' => 'Standard residential internet plan',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Residential',
                'download_speed' => 50,
                'upload_speed' => 10,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 500,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 25.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 5,
            ],
            [
                'name' => 'Home 100 Mbps',
                'internal_name' => 'home_100',
                'description' => 'High-speed residential for heavy usage',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Residential',
                'download_speed' => 100,
                'upload_speed' => 20,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 1000,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 45.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 5,
            ],
            [
                'name' => 'Business 50 Mbps',
                'internal_name' => 'business_50',
                'description' => 'Small business internet solution',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Business',
                'download_speed' => 50,
                'upload_speed' => 50,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 1000,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 79.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 7,
            ],
            [
                'name' => 'Business 200 Mbps',
                'internal_name' => 'business_200',
                'description' => 'High-speed internet for growing businesses',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Business',
                'download_speed' => 200,
                'upload_speed' => 100,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 3000,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 149.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 7,
            ],
            [
                'name' => 'Enterprise Fiber',
                'internal_name' => 'enterprise_fiber',
                'description' => 'Dedicated fiber connection for enterprises',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'fiber',
                'category' => 'Enterprise',
                'download_speed' => 1000,
                'upload_speed' => 1000,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => null,
                'data_unit' => 'GB',
                'unlimited' => true,
                'price' => 499.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 10,
            ],
            [
                'name' => 'Unlimited Premium',
                'internal_name' => 'unlimited_premium',
                'description' => 'Unlimited data with premium speeds',
                'status' => 'active',
                'visibility' => 'public',
                'type' => 'pppoe',
                'category' => 'Residential',
                'download_speed' => 200,
                'upload_speed' => 50,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => null,
                'data_unit' => 'GB',
                'unlimited' => true,
                'price' => 89.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 6,
            ],
            [
                'name' => 'Starter Plan',
                'internal_name' => 'starter',
                'description' => 'Budget-friendly basic internet',
                'status' => 'inactive',
                'visibility' => 'private',
                'type' => 'hotspot',
                'category' => 'Residential',
                'download_speed' => 5,
                'upload_speed' => 2,
                'bandwidth_unit' => 'Mbps',
                'data_limit' => 100,
                'data_unit' => 'GB',
                'unlimited' => false,
                'price' => 10.00,
                'currency' => 'USD',
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'priority' => 3,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::create($plan);
        }
    }
}
