// Dummy customer data for the ISP Management System
export const customers = [
    {
        id: 1,
        customer_code: 'CUS-2024-0001',
        type: 'individual',
        name: 'John Anderson',
        first_name: 'John',
        last_name: 'Anderson',
        company: null,
        email: 'john.anderson@email.com',
        phone: '+1 (555) 123-4567',
        mobile: '+1 (555) 987-6543',
        plan: 'Fiber 100 Mbps',
        site: 'Downtown Hub',
        router: 'Mikrotik-01',
        ip_address: '192.168.1.101',
        mac_address: 'AA:BB:CC:DD:01:01',
        status: 'active',
        balance: -45.00,
        credit_limit: 100.00,
        created_at: '2024-01-15',
        activated_at: '2024-01-16',
        address: '123 Main Street, Apt 4B',
        city: 'New York',
        state: 'NY',
        postal_code: '10001',
        country: 'United States',
        national_id: '123-45-6789',
        whatsapp: '+1 (555) 987-6543',
        pppoe_username: 'john_a',
        pppoe_password: 'Secret123',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
    {
        id: 2,
        customer_code: 'CUS-2024-0002',
        type: 'business',
        name: 'Tech Solutions Inc',
        first_name: 'John',
        last_name: 'Anderson',
        company: 'Tech Solutions Inc',
        email: 'it@techsolutions.com',
        phone: '+1 (555) 234-5678',
        mobile: '+1 (555) 876-5432',
        plan: 'Fiber 500 Mbps',
        site: 'Business Park',
        router: 'Mikrotik-02',
        ip_address: '192.168.2.50',
        mac_address: 'AA:BB:CC:DD:02:01',
        status: 'active',
        balance: 0.00,
        credit_limit: 500.00,
        created_at: '2024-02-01',
        activated_at: '2024-02-02',
        address: '456 Business Ave, Suite 100',
        city: 'San Francisco',
        state: 'CA',
        postal_code: '94105',
        country: 'United States',
        national_id: '12-3456789',
        whatsapp: '+1 (555) 876-5432',
        pppoe_username: 'techsol_01',
        pppoe_password: 'TechPass456',
        billing_cycle: 'monthly',
        tax_exempt: true,
        discount: 10,
    },
    {
        id: 3,
        customer_code: 'CUS-2024-0003',
        type: 'individual',
        name: 'Sarah Mitchell',
        first_name: 'Sarah',
        last_name: 'Mitchell',
        company: null,
        email: 'sarah.m@email.com',
        phone: '+1 (555) 345-6789',
        mobile: '+1 (555) 765-4321',
        plan: 'Fiber 50 Mbps',
        site: 'West Station',
        router: 'Cisco-01',
        ip_address: '192.168.3.201',
        mac_address: 'AA:BB:CC:DD:03:01',
        status: 'suspended',
        balance: 120.50,
        credit_limit: 50.00,
        created_at: '2024-02-10',
        activated_at: '2024-02-11',
        address: '789 Oak Lane',
        city: 'Austin',
        state: 'TX',
        postal_code: '78701',
        country: 'United States',
        national_id: '234-56-7890',
        whatsapp: '+1 (555) 765-4321',
        pppoe_username: 'sarah_m',
        pppoe_password: 'SarahPass123',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
    {
        id: 4,
        customer_code: 'CUS-2024-0004',
        type: 'individual',
        name: 'Michael Chen',
        first_name: 'Michael',
        last_name: 'Chen',
        company: null,
        email: 'mchen@email.com',
        phone: '+1 (555) 456-7890',
        mobile: '+1 (555) 654-3210',
        plan: 'Fiber 200 Mbps',
        site: 'North Tower',
        router: 'Mikrotik-03',
        ip_address: '192.168.4.85',
        mac_address: 'AA:BB:CC:DD:04:01',
        status: 'active',
        balance: -60.00,
        credit_limit: 150.00,
        created_at: '2024-02-15',
        activated_at: '2024-02-16',
        address: '321 Pine Street',
        city: 'Seattle',
        state: 'WA',
        postal_code: '98101',
        country: 'United States',
        national_id: '345-67-8901',
        whatsapp: '+1 (555) 654-3210',
        pppoe_username: 'mchen',
        pppoe_password: 'MikePass789',
        billing_cycle: 'quarterly',
        tax_exempt: false,
        discount: 5,
    },
    {
        id: 5,
        customer_code: 'CUS-2024-0005',
        type: 'business',
        name: 'Global Marketing Ltd',
        first_name: 'Jane',
        last_name: 'Smith',
        company: 'Global Marketing Ltd',
        email: 'admin@globalmarketing.com',
        phone: '+1 (555) 567-8901',
        mobile: '+1 (555) 543-2109',
        plan: 'Fiber 1 Gbps',
        site: 'Business Park',
        router: 'Cisco-02',
        ip_address: '192.168.2.100',
        mac_address: 'AA:BB:CC:DD:05:01',
        status: 'active',
        balance: 0.00,
        credit_limit: 1000.00,
        created_at: '2024-03-01',
        activated_at: '2024-03-02',
        address: '555 Commerce Blvd, Floor 12',
        city: 'Chicago',
        state: 'IL',
        postal_code: '60601',
        country: 'United States',
        national_id: '45-6789012',
        whatsapp: '+1 (555) 543-2109',
        pppoe_username: 'globalmkt',
        pppoe_password: 'GlobalSecure99',
        billing_cycle: 'yearly',
        tax_exempt: true,
        discount: 15,
    },
    {
        id: 6,
        customer_code: 'CUS-2024-0006',
        type: 'individual',
        name: 'Emma Thompson',
        first_name: 'Emma',
        last_name: 'Thompson',
        company: null,
        email: 'emma.t@email.com',
        phone: '+1 (555) 678-9012',
        mobile: '+1 (555) 432-1098',
        plan: 'Fiber 100 Mbps',
        site: 'Downtown Hub',
        router: 'Mikrotik-01',
        ip_address: '192.168.1.102',
        mac_address: 'AA:BB:CC:DD:06:01',
        status: 'pending',
        balance: 0.00,
        credit_limit: 100.00,
        created_at: '2024-03-05',
        activated_at: null,
        address: '999 Elm Court',
        city: 'Boston',
        state: 'MA',
        postal_code: '02101',
        country: 'United States',
        national_id: '567-89-0123',
        whatsapp: '+1 (555) 432-1098',
        pppoe_username: 'emma_t',
        pppoe_password: 'EmmaSecure22',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
    {
        id: 7,
        customer_code: 'CUS-2024-0007',
        type: 'individual',
        name: 'David Martinez',
        first_name: 'David',
        last_name: 'Martinez',
        company: null,
        email: 'd.martinez@email.com',
        phone: '+1 (555) 789-0123',
        mobile: '+1 (555) 321-0987',
        plan: 'Fiber 50 Mbps',
        site: 'South Station',
        router: 'Mikrotik-04',
        ip_address: '192.168.5.150',
        mac_address: 'AA:BB:CC:DD:07:01',
        status: 'terminated',
        balance: 25.00,
        credit_limit: 50.00,
        created_at: '2024-01-20',
        activated_at: '2024-01-21',
        address: '246 Maple Drive',
        city: 'Miami',
        state: 'FL',
        postal_code: '33101',
        country: 'United States',
        national_id: '678-90-1234',
        whatsapp: '+1 (555) 321-0987',
        pppoe_username: 'david_m',
        pppoe_password: 'DavePass11',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
    {
        id: 8,
        customer_code: 'CUS-2024-0008',
        type: 'business',
        name: 'Creative Design Studio',
        first_name: 'Lisa',
        last_name: 'Wang',
        company: 'Creative Design Studio',
        email: 'support@creativedesign.com',
        phone: '+1 (555) 890-1234',
        mobile: '+1 (555) 210-9876',
        plan: 'Fiber 200 Mbps',
        site: 'North Tower',
        router: 'Cisco-03',
        ip_address: '192.168.4.86',
        mac_address: 'AA:BB:CC:DD:08:01',
        status: 'active',
        balance: -80.00,
        credit_limit: 200.00,
        created_at: '2024-02-20',
        activated_at: '2024-02-21',
        address: '888 Arts District, Building C',
        city: 'Portland',
        state: 'OR',
        postal_code: '97201',
        country: 'United States',
        national_id: '78-9012345',
        whatsapp: '+1 (555) 210-9876',
        pppoe_username: 'creativedesign',
        pppoe_password: 'DesignStudio55',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 8,
    },
    {
        id: 9,
        customer_code: 'CUS-2024-0009',
        type: 'individual',
        name: 'Lisa Wang',
        first_name: 'Lisa',
        last_name: 'Wang',
        company: null,
        email: 'lwang@email.com',
        phone: '+1 (555) 901-2345',
        mobile: '+1 (555) 109-8765',
        plan: 'Fiber 100 Mbps',
        site: 'East Center',
        router: 'Mikrotik-05',
        ip_address: '192.168.6.75',
        mac_address: 'AA:BB:CC:DD:09:01',
        status: 'suspended',
        balance: 95.00,
        credit_limit: 100.00,
        created_at: '2024-03-10',
        activated_at: '2024-03-11',
        address: '135 Valley Road',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'United States',
        national_id: '890-12-3456',
        whatsapp: '+1 (555) 109-8765',
        pppoe_username: 'lwang',
        pppoe_password: 'LisaSecure88',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
    {
        id: 10,
        customer_code: 'CUS-2024-0010',
        type: 'individual',
        name: 'Robert Taylor',
        first_name: 'Robert',
        last_name: 'Taylor',
        company: null,
        email: 'r.taylor@email.com',
        phone: '+1 (555) 012-3456',
        mobile: '+1 (555) 098-7654',
        plan: 'Fiber 500 Mbps',
        site: 'West Station',
        router: 'Cisco-01',
        ip_address: '192.168.3.202',
        mac_address: 'AA:BB:CC:DD:10:01',
        status: 'active',
        balance: 0.00,
        credit_limit: 200.00,
        created_at: '2024-03-12',
        activated_at: '2024-03-13',
        address: '777 Sunset Boulevard',
        city: 'Los Angeles',
        state: 'CA',
        postal_code: '90001',
        country: 'United States',
        national_id: '901-23-4567',
        whatsapp: '+1 (555) 098-7654',
        pppoe_username: 'rtaylor',
        pppoe_password: 'RobPass33',
        billing_cycle: 'monthly',
        tax_exempt: false,
        discount: 0,
    },
];

// Stats data
export const stats = {
    total: 156,
    active: 142,
    suspended: 8,
    overdue: 6,
};

// Filter options
export const filterOptions = {
    statuses: [
        { value: '', label: 'All Statuses' },
        { value: 'active', label: 'Active' },
        { value: 'suspended', label: 'Suspended' },
        { value: 'terminated', label: 'Terminated' },
        { value: 'pending', label: 'Pending' },
    ],
    plans: [
        { value: '', label: 'All Plans' },
        { value: 'Fiber 50 Mbps', label: 'Fiber 50 Mbps' },
        { value: 'Fiber 100 Mbps', label: 'Fiber 100 Mbps' },
        { value: 'Fiber 200 Mbps', label: 'Fiber 200 Mbps' },
        { value: 'Fiber 500 Mbps', label: 'Fiber 500 Mbps' },
        { value: 'Fiber 1 Gbps', label: 'Fiber 1 Gbps' },
    ],
    sites: [
        { value: '', label: 'All Sites' },
        { value: 'Downtown Hub', label: 'Downtown Hub' },
        { value: 'Business Park', label: 'Business Park' },
        { value: 'North Tower', label: 'North Tower' },
        { value: 'South Station', label: 'South Station' },
        { value: 'West Station', label: 'West Station' },
        { value: 'East Center', label: 'East Center' },
    ],
    routers: [
        { value: '', label: 'All Routers' },
        { value: 'Mikrotik-01', label: 'Mikrotik-01' },
        { value: 'Mikrotik-02', label: 'Mikrotik-02' },
        { value: 'Mikrotik-03', label: 'Mikrotik-03' },
        { value: 'Mikrotik-04', label: 'Mikrotik-04' },
        { value: 'Mikrotik-05', label: 'Mikrotik-05' },
        { value: 'Cisco-01', label: 'Cisco-01' },
        { value: 'Cisco-02', label: 'Cisco-02' },
        { value: 'Cisco-03', label: 'Cisco-03' },
    ],
};
